feat: added check for empty body to throw error

diff --git a/.github/workflows/build_pull_request.yaml b/.github/workflows/build_pull_request.yaml
--- a/.github/workflows/build_pull_request.yaml
+++ b/.github/workflows/build_pull_request.yaml
@@ -27,6 +27,10 @@ jobs:
         run: |
           pip install -U pip
           pip install -r generators/requirements.txt
+      - if: github.event.pull_request.body == ''
+        run: |
+          echo "::error::Pull request body text can't be empty, please define which collections to test"
+          exit 1
       - if: github.event.pull_request.body == 'all'
         name: Build all
         env:
